### ISSUE TITLE
Stili bottoni ridondanti

### ISSUE THREAD

**Issue by nzambello** [italia/design-comuni-plone-theme#1]
Riporto da @nekorina: Non so quale sia la logica delle righe di questo file: https://github.com/PloneGov-IT/redturtle.agidtheme/blob/master/src/redturtle/agidtheme/theme/sass/components/plone/_buttons.scss ma cercando di metterci mano in un altro tema ho trovato molta difficoltà a capire cosa modificare (ad esempio per gli stili del .link-parent). Valuterei di fare un po' di pulizia per cercare di renderlo manutenibile nel tempo

**Comment by pnicolli** [comment]
Chiudo, altri aggiornamenti per la vecchia versione Plone 5 non sono previsti.
