### ISSUE TITLE
Could not initialize a Temporary Folder.

### ISSUE THREAD

**Issue by EliaTolin** [italia/design-comuni-plone-theme#134]
Hello, 

I started a docker compose with : 

`docker compose up`

But I see this error: 

`ERROR [Products.TemporaryFolder:52][MainThread] Could not initialize a Temporary Folder because a database was not configured to be mounted at the /temp_folder mount point`

![image](https://user-images.githubusercontent.com/60351315/236790671-7e2b69c6-b594-45e9-9b6f-e1492b8984d8.png)

How I fix this problem?

**Comment by mamico** [comment]
@EliaTolin the 'temporary folder' may not be a real problem, but we will check to remove the error/warning. 

My doubt instead is: are you trying to open the site as http://localhost or as http://localhost:3000 ? The latter probably doesn't work because of CORS.

**Comment by EliaTolin** [comment]
@mamico Thanks for you reply,

Ok I try with http://localhost and it works correctly.
But http://locahost:3000 not work.

I have a few question:

1- How setup the "Comune" configuration? For example Name, region, etc..
2- How open the editing GUI as the photo in readme? Is possible using this editing tool for change the home?

**Comment by mamico** [comment]
2. the demo site has the credentials admin:admin 

1. some information can be edited from the web interface, others are in the React application configuration.

You can edit this https://github.com/italia/design-comuni-plone-theme/blob/main/src/config/italiaConfig.js#L158 in your local project, after:

```
docker compose build
docker compose up
```

**Comment by pnicolli** [comment]
Closing as stale, drop a comment or open a new issue if other help is needed
