### ISSUE TITLE
README e redturtle.patterns.slider

### ISSUE THREAD

**Issue by nzambello** [italia/design-comuni-plone-theme#31]
Come segnalato nella #30, la dipendenza `redturtle.patterns.slider` va aggiunta manualmente al buildout, cosa  da segnare nel README.
Da controllare le altre.

Possiamo rilasciare il pacchetto?

**Comment by francescozaia** [comment]
FYI, mi ha dato lo stesso problema `collective.smartlink`, per il resto tutto liscio!

**Comment by pnicolli** [comment]
Onestamente in realtà ho un dubbio sul fatto che sia da tenere, la dipendenza `redturtle.patterns.slider`, forse dovremmo migrare ad un più semplice `collective.slick`, che era nato proprio per quel motivo. Per il resto credo sia importante mettere questo problemi tra i primi da risolvere.

**Comment by nzambello** [comment]
Il pattern è usato dalle tile collections e ha già la configurazione per slick.
Usare `collective.slick` mi piace per vari motivi e se vuoi si può pensare di rimuovere il pattern e fare tutto "a mano" via JS: avremmo il vantaggio di poterlo configurare meglio, di avere più semplicità nella gestione degli eventi (evitando mockup) e di avere più capacità di override delle impostazioni.

Certo bisognerebbe modificare tutte le tile con il carousel

**Comment by pnicolli** [comment]
Chiudo, altri aggiornamenti per la vecchia versione Plone 5 non sono previsti.
