### ISSUE TITLE
Spostare customizzazione del template di editablemenu in un add-on esterno

### ISSUE THREAD

**Issue by pnicolli** [italia/design-comuni-plone-theme#35]
Ho notato che in questo tema c'è un override del template di `collective.editablemenu` per la navigazione. Il motivo per cui è stato fatto, cioè l'aggiungere il bottone per gestire la navigazione su dispositivi mobili, è valido, ma quel menù non è una dipendenza diretta di questo tema. Possiamo benissimo usare questo tema con il menù base di Plone, non dimentichiamolo.

Per l'integrazione di quel menù abbiamo un add-on (nome temporaneo: `redturtle.agid.megamenu`), che al momento sta sul nostro bitbucket privato, a cui potremmo aggiungere questo override e potremmo pubblicarlo qui su github e su pypi, perché mi sembra che funzioni correttamente.

Cosa ne pensate?

**Comment by nzambello** [comment]
Ok, quell'addon è nato appositamente per questo.
Possiamo senz'altro spostare l'override del template lì, ma bisogna tener conto dei temi fatti prima dell'addon: bisogna fare un po' di refactoring su di essi per integrare quell'addon.

Sarebbe tutto più uniforme e più pulito, bisogna tener conto dei tempi per allinearli.

**Comment by yurj** [comment]
Salve,

 ci sono novità per questo problema? Nel frattempo, si può togliere questo override nel caso non si usi l'editable menu?

**Comment by pnicolli** [comment]
Chiudo, altri aggiornamenti per la vecchia versione Plone 5 non sono previsti.
