### ISSUE TITLE
Aggiunta di questo tema tra quelli disponibili

### ISSUE THREAD

**Issue by pnicolli** [italia/design-comuni-plone-theme#74]
Questo tema è al momento in produzione già su diversi siti da circa due anni ed è considerato stabile.

Chiediamo l'aggiunta del tema tra quelli effettivamente disponibili per l'uso alla pagina https://developers.italia.it/it/designers, dove al momento Plone è citato solo come "in considerazione".

Il discorso dell'aggiunta di questo tema tra quelli disponibili era stato iniziato con Riccardo Iaconelli circa un anno fa e siamo qui ora ad aprire questa issue per cercare di arrivare ad una soluzione per questa questione, come suggerito da @sbronzolo pochi giorni fa parlando con @stemrc.

**Comment by sbronzolo** [comment]
Ciao, nella nostra conversazione avevamo parlato di una evoluzione alle
linee guida di design 2019 che può essere fatta usando lo UI kit 2019 e/o
il relativo kit di sviluppo Bootstrap Italia 2019.1


Il giorno martedì 2 luglio 2019, Piero Nicolli <notifications@github.com>
ha scritto:

**Comment by stemrc** [comment]
@sbronzolo in coda alla call avevamo anche parlato del fatto che il tema plone è pronto da tempo ma non viene citato tra i temi disponibili. Mi dicevi di aprirti una isssue per chiederti di aggiungerlo nella pagina https://developers.italia.it/it/designers . Mi sfugge qualcosa?

**Comment by sbronzolo** [comment]
Il tema di cui parli risale al 2017 e di conseguenza non è aggiornato alle
linee guida 2019, allo UI kit https://designers.italia.it/kit/ui-kit/
L'adozione dell'evoluzione dello UI kit può essere fatta utilizzando
https://italia.github.io/bootstrap-italia/ stabile da gennaio 2019

p.s.: per quanto riguarda i comuni invece esiste uno starter kit più
dettagliato, con una descrizione completa dell'architettura informativa e
un rilascio di tutti i template html basati su bootstrap italia . Il kit
comuni sarà rilasciato a luglio in forma stabile @francescozaia

Il giorno mer 3 lug 2019 alle ore 08:55 Stefano Marchetti <
notifications@github.com> ha scritto:

**Comment by sbronzolo** [comment]
la cosa è descritta sul nostro sito
https://designers.italia.it/kit/web-development-kit/

Il giorno mer 3 lug 2019 alle ore 09:44 Lorenzo Fabbri <
lorenzofabbri77@gmail.com> ha scritto:

**Comment by stemrc** [comment]
Grazie @sbronzolo . Evidentemente non ci eravamo capiti :)

Intanto procediamo per l'implementazione del tema conforme alle linea guida 2019 anche confrontandoci con gli Enti che intendono adottarle.
Attendiamo quindi la versione stabile dello starter kit dettagliato per i Comuni.

**Comment by sbronzolo** [comment]
Bene, stiamo completando la documentazione in vista del rilascio previsto
nei prossimi giorni.
Lorenzo

Il giorno mar 23 lug 2019 alle ore 19:57 Stefano Marchetti <
notifications@github.com> ha scritto:

**Comment by stemrc** [comment]
ottima notizia @sbronzolo !
Stefano

**Comment by pnicolli** [comment]
@sbronzolo Lo sviluppo del tema Plone secondo le linee guida 2019 è in corso sul nuovo frontend di Plone basato su React che si chiama https://github.com/plone/volto.
Il repository del tema basato sulle nuove linee guida è attualmente qui: https://github.com/RedTurtle/design-volto-theme
Vorremmo iniziare a spostarlo sotto italia e mettere un riferimento nel Readme di questo repository al fatto che la versione nuova è in via di sviluppo.
Posso attivare uno di voi sul repository in modo che possiamo effettuare il trasferimento. Come ci muoviamo?

**Comment by pnicolli** [comment]
Qualcuno può darmi notizie su questa cosa? Vorremmo capire come portare avanti il discorso. Se dobbiamo contattare qualcuno che non è qui, è già un'informazione utile.
Grazie

**Comment by pnicolli** [comment]
Chiudo lasciando un riferimento alla discussione avvenuta su altra PR: https://github.com/italia/design-comuni-docs/pull/64
