### ISSUE TITLE
mobile navigation menu not available, both Plone 5.1 and Plone 5.2

### ISSUE THREAD

**Issue by yurj** [italia/design-comuni-plone-theme#98]
Hi!
 after the theme installation, there's no more menu available when using "mobile" (or just restrict the browser window), both Plone 5.1 and Plone 5.2. Installing editablemenu it appears but the zindex and css problem make it unclickable.

I suggest to add:
"Questo prodotto è stato testato su Plone >= 5.0.7 _e <= Plone 5.0.10_.

**Comment by nzambello** [comment]
Hi, in RedTurtle we have two common options: standard Plone navigation (by default and working with this theme) or 
But if you are using editablemenu, we actually have to style the integration yourself.
In this theme we have that integration but we left the styles to site projects.

Regarding Plone versions, we have this running on Plone 5.2 on python3 (compatible from v5).

**Comment by VanLoon-dev** [comment]
I installed add-on on Plone 5.2, python 3.7, but mobile menu is not available.

**Comment by yurj** [comment]
"In this theme we have that integration but we left the styles to site projects."

Ok, thanks!

**Comment by yurj** [comment]
> we have two common options: standard Plone navigation (by default and working with this theme) 

Now, with the lastest commits, there's no navigation in mobile, even the standard one is missing. Plone 5.2.4 with only design.plone.theme installed.

**Comment by carlo9999999** [comment]
same problem on plone 5.2.1 mobile menu is not avaiable

**Comment by pnicolli** [comment]
Chiudo, altri aggiornamenti per la vecchia versione Plone 5 non sono previsti.
